### ISSUE TITLE
Recover from panics in exporter and receiver code path

### ISSUE THREAD

**Issue by jmacd** [f5/otel-arrow-adapter#121]
Make sure that a panic in the Arrow producer or consumer does not kill the collector.

Note that the Arrow exporter component already has recover() logic in place, but the receiver component does not.

This is to acknowledge both that this schema maintenance is complex and that it contains panics for scenarios that should not occur, see #108.

**Comment by jmacd** [comment]
Have an example of this in the receiver just now:

```
panic: runtime error: index out of range [-1] [recovered]
	panic: runtime error: index out of range [-1]

goroutine 287 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	go.opentelemetry.io/otel/sdk@v1.15.1/trace/span.go:383 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000003080, {0x0, 0x0, 0x7f5ab8487108?})
	go.opentelemetry.io/otel/sdk@v1.15.1/trace/span.go:415 +0x99e
panic({0x3be6ae0, 0xc00064f7a0})
	runtime/panic.go:884 +0x213
github.com/apache/arrow/go/v12/arrow/array.(*Struct).Field(...)
	github.com/apache/arrow/go/v12@v12.0.0-20230404000714-f02d35119ae6/arrow/array/struct.go:82
github.com/f5/otel-arrow-adapter/pkg/otel/metrics/otlp.AppendUnivariateEHistogramDataPointBucketsInto({0x4670070?}, 0xc00203cc30?, 0x8?, 0x0?)
	github.com/f5/otel-arrow-adapter@v0.0.0-20230530232012-6efcf0962e54/pkg/otel/metrics/otlp/ehistogram_dpb.go:53 +0x31b
github.com/f5/otel-arrow-adapter/pkg/otel/metrics/otlp.EHistogramDataPointsStoreFrom({0x4670070?, 0xc00203cc30}, 0xc00167b510, 0xc00167b4a0)
	github.com/f5/otel-arrow-adapter@v0.0.0-20230530232012-6efcf0962e54/pkg/otel/metrics/otlp/ehistogram.go:239 +0x66d
github.com/f5/otel-arrow-adapter/pkg/otel/metrics/otlp.RelatedDataFrom({0xc001f01d80, 0x6, 0x4?})
	github.com/f5/otel-arrow-adapter@v0.0.0-20230530232012-6efcf0962e54/pkg/otel/metrics/otlp/related_data.go:249 +0xac5
github.com/f5/otel-arrow-adapter/pkg/otel/arrow_record.(*Consumer).MetricsFrom(0xc000338870?, 0x4658ff0?)
	github.com/f5/otel-arrow-adapter@v0.0.0-20230530232012-6efcf0962e54/pkg/otel/arrow_record/consumer.go:90 +0x65
github.com/f5/otel-arrow-adapter/collector/gen/receiver/otlpreceiver/internal/arrow.(*Receiver).processRecords(0xc0016ecbb0, {0x4658ff0, 0xc001f1c420}, {0x4659300, 0xc001ecdb78}, 0xc0008320e0)
	github.com/f5/otel-arrow-adapter@v0.0.0-20230530232012-6efcf0962e54/collector/gen/receiver/otlpreceiver/internal/arrow/arrow.go:375 +0x489
github.com/f5/otel-arrow-adapter/collector/gen/receiver/otlpreceiver/internal/arrow.(*Receiver).anyStream(0xc0016ecbb0, {0x7f5a90b13918, 0xc001669d60})
	github.com/f5/otel-arrow-adapter@v0.0.0-20230530232012-6efcf0962e54/collector/gen/receiver/otlpreceiver/internal/arrow/arrow.go:325 +0x24f
github.com/f5/otel-arrow-adapter/collector/gen/receiver/otlpreceiver/internal/arrow.(*Receiver).ArrowMetrics(0xc000799740?, {0x4666c10?, 0xc001669d60})
	github.com/f5/otel-arrow-adapter@v0.0.0-20230530232012-6efcf0962e54/collector/gen/receiver/otlpreceiver/internal/arrow/arrow.go:272 +0x45
github.com/f5/otel-arrow-adapter/api/experimental/arrow/v1._ArrowMetricsService_ArrowMetrics_Handler({0x3d0ac40?, 0xc0016ecbb0}, {0x4661138?, 0xc001675ce0})
	github.com/f5/otel-arrow-adapter@v0.0.0-20230530232012-6efcf0962e54/api/experimental/arrow/v1/arrow_service_grpc.pb.go:458 +0x9f
go.opentelemetry.io/collector/config/configgrpc.enhanceStreamWithClientInformation.func1({0x3d0ac40, 0xc0016ecbb0}, {0x46611c8, 0xc001f1c3c0?}, 0xc001f1c3c0?, 0x40e4c28)
	go.opentelemetry.io/collector@v0.78.2/config/configgrpc/configgrpc.go:406 +0x12b
google.golang.org/grpc.getChainStreamHandler.func1({0x3d0ac40, 0xc0016ecbb0}, {0x46611c8, 0xc001f1c3c0})
	google.golang.org/grpc@v1.55.0/server.go:1483 +0xb9
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamServerInterceptor.func1({0x3d0ac40, 0xc0016ecbb0}, {0x46612e8, 0xc000338ff0}, 0xc001ecdb48, 0xc001f00a80)
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.41.1/interceptor.go:437 +0x43a
google.golang.org/grpc.chainStreamInterceptors.func1({0x3d0ac40, 0xc0016ecbb0}, {0x46612e8, 0xc000338ff0}, 0x32e98a0?, 0xc001669c90?)
	google.golang.org/grpc@v1.55.0/server.go:1474 +0x8f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0008c8b40, {0x466b3e0, 0xc000688ea0}, 0xc0016b0120, 0xc001950390, 0x67876e0, 0x0)
	google.golang.org/grpc@v1.55.0/server.go:1638 +0x1363
google.golang.org/grpc.(*Server).handleStream(0xc0008c8b40, {0x466b3e0, 0xc000688ea0}, 0xc0016b0120, 0x0)
	google.golang.org/grpc@v1.55.0/server.go:1718 +0x9f0
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.55.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.55.0/server.go:957 +0x18c
```
